name: Branch and Commit Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the entire commit history

      - name: Check Branch Name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          fi

          # Allow branches starting with deployment/
          if [[ $BRANCH_NAME == deployment/* ]]; then
            echo "✅ Branch name is correctly formatted (deployment): $BRANCH_NAME"
            exit 0
          fi

          PATTERN="^(feature|bugfix|merge)\/PAYB-[0-9]+(-(dev|uat|stage|master))?$"
          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch name must follow one of these formats:"
            echo "  - feature/PAYB-1234"
            echo "  - bugfix/PAYB-1234"
            echo "  - merge/PAYB-1234-dev, merge/PAYB-1234-uat, merge/PAYB-1234-stage, merge/PAYB-1234-master"
            echo "  - deployment/<any-name>"
            exit 1
          else
            echo "✅ Branch name is correctly formatted: $BRANCH_NAME"
          fi

      - name: Check Commit Messages
        run: |
          git fetch origin

          BASE_BRANCH="$GITHUB_BASE_REF"
          if [[ $GITHUB_EVENT_NAME != "pull_request" ]]; then
            BASE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          fi

          COMMITS=$(git log origin/$BASE_BRANCH..HEAD --pretty=format:"%s" --no-merges)

          PATTERN="^PAYB-[0-9]+ - .+$"
          DESC_PATTERN="^PAYB-[0-9]+ - .{10,}$"

          while IFS= read -r COMMIT_MSG; do
            if [[ -z "$COMMIT_MSG" ]]; then
              echo "⚠️ Empty commit message found."
              continue
            fi

            if [[ ! $COMMIT_MSG =~ $PATTERN ]]; then
              echo "❌ Invalid commit message: $COMMIT_MSG"
              echo "Commit message must follow this format: 'PAYB-1234 - Description'"
              exit 1
            elif [[ ! $COMMIT_MSG =~ $DESC_PATTERN ]]; then
              echo "❌ Commit message is too short. It should be at least 10 characters long after the task ID."
              exit 1
            else
              echo "✅ Commit message is correctly formatted and descriptive: $COMMIT_MSG"
            fi
          done <<< "$COMMITS"